baseurl = "http://blog.guoyong.me/"
languageCode = "zh-cn"
title = "不上班的程序员"
author = "wolfg1969"
theme = "hyde"
canonifyurls = true
pygmentsuseclasses = true
# pygmentsstyle = "monokai"
pygmentscodefences = true
hasCJKLanguage = true

[params]
  themeColor = "theme-base-0b"
  # layoutReverse = true
  description = "女儿对同学说：“我爸爸的工作是程序员，在家工作。”"
  author = "wolfg1969"
  copyright = "Copyright &#xA9; 2016 wolfg1969. All Rights Reserved."
  homeTitle = "文章列表"
